INSERT INTO PRODUCT VALUES(1,'COBERTURA', 50,3);
INSERT INTO PRODUCT VALUES(2,'FULL COBERTURA', 50,2);
INSERT INTO PRODUCT VALUES(3,'BAJA COBERTURA', 20,3);
INSERT INTO PRODUCT VALUES(4,'MEGA COBERTURA', 10,4);
INSERT INTO PRODUCT VALUES(5,'FULL COBERTURA SUPER DUPER', 12,5);
INSERT INTO PRODUCT VALUES(6,'SUPER AVANCE', 20,6);


	
